# Generated by Django 5.0.4 on 2026-02-25 11:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0003_alter_company_options_alter_company_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_code', models.CharField(help_text='Unique product/material code from the accounting system.', max_length=100, verbose_name='Product Code')),
                ('lab_code', models.CharField(blank=True, max_length=100, null=True, verbose_name='Lab / Supplier Code')),
                ('product_name', models.CharField(max_length=500, verbose_name='Product Name')),
                ('category', models.CharField(blank=True, help_text='Product category/family (e.g. Fire Detection, Addressable).', max_length=255, null=True, verbose_name='Category')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='companies.company', verbose_name='Company')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'db_table': 'products_product',
                'ordering': ['category', 'product_name'],
                'unique_together': {('company', 'product_code')},
            },
        ),
    ]
