# Generated by Django 5.0.4 on 2026-03-16 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_insights', '0001 initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertresolution',
            name='notes',
            field=models.TextField(blank=True, default='', help_text='Optional comment added by the agent when resolving.', verbose_name='Resolution Notes'),
        ),
    ]
