# Generated by Django 5.0.4 on 2026-02-20 03:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, help_text="Email utilisé lors de la tentative (même si l'utilisateur n'existe pas).", max_length=254)),
                ('ip_address', models.GenericIPAddressField(db_index=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('is_successful', models.BooleanField(default=False)),
                ('failure_reason', models.CharField(blank=True, choices=[('invalid_credentials', 'Identifiants incorrects'), ('account_pending', "Compte en attente d'approbation"), ('account_rejected', 'Compte rejeté'), ('account_suspended', 'Compte suspendu'), ('rate_limited', 'Trop de tentatives')], max_length=100, null=True)),
                ('attempted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tentative de Connexion',
                'verbose_name_plural': 'Tentatives de Connexion',
                'db_table': 'token_login_attempt',
                'ordering': ['-attempted_at'],
            },
        ),
        migrations.CreateModel(
            name='ActiveSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('refresh_token_jti', models.CharField(db_index=True, help_text='JTI du refresh token lié à cette session.', max_length=255, unique=True)),
                ('device_fingerprint', models.CharField(help_text="Empreinte hashée de l'appareil (User-Agent + autres données).", max_length=255)),
                ('device_name', models.CharField(blank=True, help_text="Nom lisible de l'appareil (ex: Chrome sur Windows).", max_length=255, null=True)),
                ('ip_address', models.GenericIPAddressField(help_text='Adresse IP lors de la connexion.')),
                ('last_activity', models.DateTimeField(auto_now=True, help_text='Dernière activité détectée sur cette session.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_current', models.BooleanField(default=False, help_text="Indique si c'est la session active de la requête courante.")),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Session Active',
                'verbose_name_plural': 'Sessions Actives',
                'db_table': 'token_active_session',
                'ordering': ['-last_activity'],
            },
        ),
        migrations.CreateModel(
            name='RefreshTokenRotation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('old_token_jti', models.CharField(help_text="JTI (JWT ID) de l'ancien refresh token révoqué lors de la rotation.", max_length=255, unique=True)),
                ('new_token_jti', models.CharField(help_text='JTI du nouveau refresh token généré après rotation.', max_length=255)),
                ('rotated_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('device_fingerprint', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refresh_token_rotations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rotation Refresh Token',
                'verbose_name_plural': 'Rotations Refresh Tokens',
                'db_table': 'token_refresh_rotation',
                'ordering': ['-rotated_at'],
            },
        ),
        migrations.CreateModel(
            name='TokenBlacklist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token_jti', models.CharField(db_index=True, help_text='JWT ID unique du token révoqué.', max_length=255, unique=True)),
                ('token_type', models.CharField(choices=[('access', 'Access Token'), ('refresh', 'Refresh Token'), ('temporary', 'Temporary Token')], default='refresh', max_length=20)),
                ('revoked_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(help_text="Date d'expiration du token. Utilisé pour le nettoyage automatique via Celery.")),
                ('reason', models.CharField(choices=[('logout', 'Déconnexion'), ('logout_all', 'Déconnexion de tous les appareils'), ('password_changed', 'Changement de mot de passe'), ('password_reset', 'Réinitialisation de mot de passe'), ('admin_revoked', "Révocation par l'administrateur"), ('suspicious_activity', 'Activité suspecte détectée'), ('token_reuse', "Réutilisation d'un ancien token")], default='logout', max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blacklisted_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Token Blacklisté',
                'verbose_name_plural': 'Tokens Blacklistés',
                'db_table': 'token_blacklist',
                'ordering': ['-revoked_at'],
            },
        ),
    ]
