# Generated by Django 5.0.4 on 2026-02-25 11:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0003_alter_company_options_alter_company_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=500, verbose_name='Customer Name')),
                ('account_code', models.CharField(help_text='Unique accounting system identifier (e.g. 113102).', max_length=100, verbose_name='Account Code')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Address')),
                ('area_code', models.CharField(blank=True, max_length=100, null=True, verbose_name='Area Code')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Phone')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='companies.company', verbose_name='Company')),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'db_table': 'customers_customer',
                'ordering': ['customer_name'],
                'unique_together': {('company', 'account_code')},
            },
        ),
    ]
