# Generated by Django 5.0.4 on 2026-02-25 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['name'], 'verbose_name': 'Customer', 'verbose_name_plural': 'Customers'},
        ),
        migrations.RemoveField(
            model_name='customer',
            name='customer_name',
        ),
        migrations.AddField(
            model_name='customer',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Set to False when absent from import — preserves FK integrity.', verbose_name='Active'),
        ),
        migrations.AddField(
            model_name='customer',
            name='name',
            field=models.CharField(blank=True, help_text='اسم العميل', max_length=500, null=True, verbose_name='Customer name'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='account_code',
            field=models.CharField(db_index=True, help_text='رمز الحساب', max_length=50, verbose_name='Account code'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.TextField(blank=True, help_text='العنوان التفصيلي', null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='area_code',
            field=models.CharField(blank=True, help_text='رمز المنطقة', max_length=50, null=True, verbose_name='Area code'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, help_text='رقم الهاتف1', max_length=50, null=True, verbose_name='Phone'),
        ),
        migrations.AlterModelTable(
            name='customer',
            table=None,
        ),
    ]
