# Generated by Django 5.0.4 on 2026-02-25 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_alter_customer_options_remove_customer_customer_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(default='', help_text='اسم العميل', max_length=500, verbose_name='Customer name'),
            preserve_default=False,
        ),
    ]
