# Generated by Django 5.0.4 on 2026-02-25 11:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0003_alter_company_options_alter_company_address_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_type', models.CharField(choices=[('branches', 'Branches'), ('customers', 'Customers'), ('movements', 'Material Movements'), ('inventory', 'Inventory Snapshot'), ('aging', 'Aging Receivables')], max_length=30, verbose_name='File Type')),
                ('original_filename', models.CharField(max_length=500, verbose_name='Original Filename')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('success', 'Success'), ('partial', 'Partial Success'), ('failed', 'Failed')], default='pending', max_length=20, verbose_name='Status')),
                ('row_count', models.PositiveIntegerField(default=0, verbose_name='Rows Processed')),
                ('success_count', models.PositiveIntegerField(default=0, verbose_name='Rows Successfully Imported')),
                ('error_count', models.PositiveIntegerField(default=0, verbose_name='Rows With Errors')),
                ('error_details', models.JSONField(blank=True, default=list, help_text='List of {row, error} dicts for failed rows.', verbose_name='Error Details')),
                ('import_context', models.JSONField(blank=True, default=dict, verbose_name='Import Context')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Started At')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed At')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_logs', to='companies.company', verbose_name='Company')),
                ('imported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_logs', to=settings.AUTH_USER_MODEL, verbose_name='Imported By')),
            ],
            options={
                'verbose_name': 'Import Log',
                'verbose_name_plural': 'Import Logs',
                'db_table': 'data_import_log',
                'ordering': ['-started_at'],
            },
        ),
    ]
