# Generated by Django 5.0.4 on 2026-02-21 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='is_active',
            field=models.BooleanField(default=True, help_text="Désactiver pour suspendre l'accès à toute la société.", verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(help_text='Nom officiel de la société.', max_length=255, unique=True, verbose_name='Nom de la société'),
        ),
    ]
