# Generated by Django 5.0.4 on 2026-03-04 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_alter_company_options_alter_company_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='city',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='company',
            name='country',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='company',
            name='current_erp',
            field=models.CharField(blank=True, default='', help_text='ERP or software currently used by the company.', max_length=100, verbose_name='Current ERP'),
        ),
    ]
