# Generated by Django 5.0.4 on 2026-03-04 22:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KPISnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('computed_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('report_date', models.DateField(blank=True, db_index=True, null=True)),
                ('taux_clients_credit', models.FloatField(default=0.0)),
                ('taux_credit_total', models.FloatField(default=0.0)),
                ('taux_impayes', models.FloatField(default=0.0)),
                ('dmp', models.FloatField(default=0.0, verbose_name='Délai Moyen de Paiement (jours)')),
                ('taux_recouvrement', models.FloatField(default=0.0)),
                ('total_customers', models.IntegerField(default=0)),
                ('credit_customers', models.IntegerField(default=0)),
                ('grand_total_receivables', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('overdue_amount', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('ca_credit', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('ca_total', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
            ],
            options={
                'verbose_name': 'KPI Snapshot',
                'verbose_name_plural': 'KPI Snapshots',
                'ordering': ['-computed_at'],
            },
        ),
        migrations.CreateModel(
            name='RiskyCustomerSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveSmallIntegerField()),
                ('account_code', models.CharField(max_length=50)),
                ('customer_name', models.CharField(blank=True, max_length=255)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('current', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('overdue_total', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('risk_score', models.CharField(choices=[('low', 'Faible'), ('medium', 'Moyen'), ('high', 'Élevé'), ('critical', 'Critique')], default='low', max_length=10)),
                ('overdue_percentage', models.FloatField(default=0.0)),
                ('dmp_days', models.FloatField(default=0.0)),
                ('buckets', models.JSONField(default=dict)),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risky_customers', to='kpi.kpisnapshot')),
            ],
            options={
                'verbose_name': 'Risky Customer Snapshot',
                'verbose_name_plural': 'Risky Customer Snapshots',
                'ordering': ['snapshot', 'rank'],
            },
        ),
    ]
