# Generated by Django 5.0.4 on 2026-03-04 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', 'migration_0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialmovement',
            name='movement_type',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100, verbose_name='Movement Type'),
        ),
    ]
