# Generated by Django 5.0.4 on 2026-02-25 11:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0002_alter_branch_options_alter_branch_address_and_more'),
        ('companies', '0003_alter_company_options_alter_company_address_and_more'),
        ('customers', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialMovement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(blank=True, max_length=255, null=True, verbose_name='Category')),
                ('material_code', models.CharField(max_length=100, verbose_name='Material Code')),
                ('lab_code', models.CharField(blank=True, max_length=100, null=True, verbose_name='Lab Code')),
                ('material_name', models.CharField(max_length=500, verbose_name='Material Name')),
                ('movement_date', models.DateField(db_index=True, verbose_name='Movement Date')),
                ('movement_type', models.CharField(choices=[('sale', 'Sale'), ('purchase', 'Purchase'), ('opening_balance', 'Opening Balance'), ('sales_return', 'Sales Return'), ('purchase_return', 'Purchase Return'), ('main_entry', 'Main Entry'), ('main_exit', 'Main Exit'), ('other', 'Other')], db_index=True, default='other', max_length=30, verbose_name='Movement Type')),
                ('movement_type_raw', models.CharField(blank=True, help_text='Original Arabic value from Excel for reference.', max_length=100, null=True, verbose_name='Movement Type (Original Arabic)')),
                ('qty_in', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True, verbose_name='Quantity In')),
                ('price_in', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True, verbose_name='Unit Price In (LYD)')),
                ('total_in', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True, verbose_name='Total In (LYD)')),
                ('qty_out', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True, verbose_name='Quantity Out')),
                ('price_out', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True, verbose_name='Unit Price Out (LYD)')),
                ('total_out', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True, verbose_name='Total Out (LYD)')),
                ('balance_price', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True, verbose_name='Balance Price (LYD)')),
                ('branch_name', models.CharField(blank=True, help_text='Raw branch name from Excel (resolved to Branch FK when possible).', max_length=255, null=True, verbose_name='Branch Name')),
                ('customer_name', models.CharField(blank=True, help_text='Raw customer name from Excel.', max_length=500, null=True, verbose_name='Customer Name')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements', to='branches.branch', verbose_name='Branch')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_movements', to='companies.company', verbose_name='Company')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements', to='customers.customer', verbose_name='Customer')),
                ('product', models.ForeignKey(blank=True, help_text='Linked product (resolved from product_code during import).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements', to='products.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Material Movement',
                'verbose_name_plural': 'Material Movements',
                'db_table': 'transactions_movement',
                'ordering': ['-movement_date', 'material_code'],
                'indexes': [models.Index(fields=['company', 'movement_date'], name='transaction_company_07c04e_idx'), models.Index(fields=['company', 'movement_type'], name='transaction_company_12bb3d_idx'), models.Index(fields=['company', 'material_code'], name='transaction_company_58258b_idx')],
            },
        ),
    ]
