# Generated by Django 5.0.4 on 2026-02-25 11:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0003_alter_company_options_alter_company_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventorySnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('snapshot_date', models.DateField(help_text='Date of this inventory snapshot (e.g. 2025-12-31).', verbose_name='Snapshot Date')),
                ('qty_alkarimia', models.DecimalField(decimal_places=4, default=0, max_digits=14, verbose_name='Qty — Al-Karimia Branch')),
                ('qty_benghazi', models.DecimalField(decimal_places=4, default=0, max_digits=14, verbose_name='Qty — Benghazi Warehouse')),
                ('qty_mazraa', models.DecimalField(decimal_places=4, default=0, max_digits=14, verbose_name='Qty — Al-Mazraa Warehouse')),
                ('qty_dahmani', models.DecimalField(decimal_places=4, default=0, max_digits=14, verbose_name='Qty — Dahmani Showroom')),
                ('qty_janzour', models.DecimalField(decimal_places=4, default=0, max_digits=14, verbose_name='Qty — Janzour Showroom')),
                ('qty_misrata', models.DecimalField(decimal_places=4, default=0, max_digits=14, verbose_name='Qty — Misrata Branch')),
                ('value_mazraa', models.DecimalField(decimal_places=4, default=0, max_digits=18, verbose_name='Value — Al-Mazraa Warehouse')),
                ('value_dahmani', models.DecimalField(decimal_places=4, default=0, max_digits=18, verbose_name='Value — Dahmani Showroom')),
                ('value_janzour', models.DecimalField(decimal_places=4, default=0, max_digits=18, verbose_name='Value — Janzour Showroom')),
                ('value_alkarimia', models.DecimalField(decimal_places=4, default=0, max_digits=18, verbose_name='Value — Al-Karimia Branch')),
                ('value_misrata', models.DecimalField(decimal_places=4, default=0, max_digits=18, verbose_name='Value — Misrata Branch')),
                ('total_qty', models.DecimalField(decimal_places=4, default=0, max_digits=14, verbose_name='Total Quantity')),
                ('cost_price', models.DecimalField(decimal_places=4, default=0, help_text='Company cost price per unit.', max_digits=14, verbose_name='Cost Price (LYD)')),
                ('total_value', models.DecimalField(decimal_places=4, default=0, max_digits=18, verbose_name='Total Value (LYD)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_snapshots', to='companies.company', verbose_name='Company')),
            ],
            options={
                'verbose_name': 'Inventory Snapshot',
                'verbose_name_plural': 'Inventory Snapshots',
                'db_table': 'inventory_snapshot',
                'ordering': ['-snapshot_date', 'product__category', 'product__product_name'],
            },
        ),
    ]
