# Generated by Django 5.0.4 on 2026-02-25 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorysnapshot',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_snapshots', to='products.product', verbose_name='Product'),
        ),
        migrations.AlterUniqueTogether(
            name='inventorysnapshot',
            unique_together={('company', 'product', 'snapshot_date')},
        ),
    ]
