# Generated by Django 5.0.4 on 2026-03-11 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_dynamic_branch_values'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorysnapshot',
            name='branch_quantities',
            field=models.JSONField(blank=True, default=dict, help_text='Dynamic branch quantities: {branch_name: value, ...}', verbose_name='Branch Quantities'),
        ),
        migrations.DeleteModel(
            name='InventoryBranchValue',
        ),
    ]
