# Generated by Django 5.0.4 on 2026-03-11 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_flatten_branch_quantities'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventorysnapshot',
            name='branch_quantities',
        ),
        migrations.AddField(
            model_name='inventorysnapshot',
            name='branch_name',
            field=models.CharField(blank=True, default='', help_text='Plain-text branch name read from the Excel file. No FK constraint.', max_length=100, verbose_name='Branch Name'),
        ),
    ]
