# Generated by Django 5.0.4 on 2026-03-11 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_inventory_company_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorysnapshot',
            name='label',
            field=models.CharField(blank=True, default='', help_text="Optional human-readable label (e.g. 'Inventaire 2025 T1').", max_length=200, verbose_name='Label'),
        ),
    ]
