# Generated by Django 5.0.4 on 2026-02-25 11:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0003_alter_company_options_alter_company_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgingReceivable',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('account', models.CharField(help_text='Full account label from the Excel file.', max_length=500, verbose_name='Account')),
                ('account_code', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='Account Code')),
                ('report_date', models.DateField(help_text='Date of the aging report snapshot.', verbose_name='Report Date')),
                ('current', models.DecimalField(decimal_places=4, default=0, max_digits=18, verbose_name='Current (not yet due)')),
                ('d1_30', models.DecimalField(decimal_places=4, default=0, max_digits=18, verbose_name='1–30 Days')),
                ('d31_60', models.DecimalField(decimal_places=4, default=0, max_digits=18, verbose_name='31–60 Days')),
                ('d61_90', models.DecimalField(decimal_places=4, default=0, max_digits=18, verbose_name='61–90 Days')),
                ('d91_120', models.DecimalField(decimal_places=4, default=0, max_digits=18, verbose_name='91–120 Days')),
                ('d121_150', models.DecimalField(decimal_places=4, default=0, max_digits=18, verbose_name='121–150 Days')),
                ('d151_180', models.DecimalField(decimal_places=4, default=0, max_digits=18, verbose_name='151–180 Days')),
                ('d181_210', models.DecimalField(decimal_places=4, default=0, max_digits=18, verbose_name='181–210 Days')),
                ('d211_240', models.DecimalField(decimal_places=4, default=0, max_digits=18, verbose_name='211–240 Days')),
                ('d241_270', models.DecimalField(decimal_places=4, default=0, max_digits=18, verbose_name='241–270 Days')),
                ('d271_300', models.DecimalField(decimal_places=4, default=0, max_digits=18, verbose_name='271–300 Days')),
                ('d301_330', models.DecimalField(decimal_places=4, default=0, max_digits=18, verbose_name='301–330 Days')),
                ('over_330', models.DecimalField(decimal_places=4, default=0, max_digits=18, verbose_name='Over 330 Days')),
                ('total', models.DecimalField(decimal_places=4, default=0, max_digits=18, verbose_name='Total Balance (LYD)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aging_receivables', to='companies.company', verbose_name='Company')),
            ],
            options={
                'verbose_name': 'Aging Receivable',
                'verbose_name_plural': 'Aging Receivables',
                'db_table': 'aging_receivable',
                'ordering': ['-total', 'account'],
            },
        ),
    ]
