# Generated by Django 5.0.4 on 2026-02-25 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aging', '0001_initial'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agingreceivable',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aging_records', to='customers.customer', verbose_name='Customer'),
        ),
        migrations.AlterUniqueTogether(
            name='agingreceivable',
            unique_together={('company', 'account_code', 'report_date')},
        ),
    ]
