# Generated by Django 5.0.4 on 2026-03-11 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aging', '0004_aging_snapshot'),
        ('companies', '0004_company_city_company_country_company_current_erp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agingreceivable',
            name='company',
            field=models.ForeignKey(help_text='Denormalized from snapshot for efficient filtering.', on_delete=django.db.models.deletion.CASCADE, related_name='aging_receivables', to='companies.company', verbose_name='Company'),
        ),
    ]
