# Generated by Django 5.0.4 on 2026-03-04 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0002_alter_branch_options_alter_branch_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='branch',
            name='current_erp',
            field=models.CharField(blank=True, help_text='ERP or business software currently used.', max_length=100, null=True, verbose_name='Current ERP'),
        ),
    ]
