# Generated by Django 5.0.4 on 2026-03-11 21:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0003_branch_country_branch_current_erp'),
        ('companies', '0004_company_city_company_country_company_current_erp'),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchAlias',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alias', models.CharField(help_text='Exact string as it appears in the imported file.', max_length=255, verbose_name='Raw name from Excel')),
                ('auto_matched', models.BooleanField(default=False, help_text='True = resolved automatically via fuzzy matching.', verbose_name='Auto-matched')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('branch', models.ForeignKey(blank=True, help_text='Null = unresolved. Admin must link it via the API.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aliases', to='branches.branch', verbose_name='Canonical branch')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_aliases', to='companies.company', verbose_name='Company')),
            ],
            options={
                'verbose_name': 'Branch Alias',
                'verbose_name_plural': 'Branch Aliases',
                'db_table': 'branches_alias',
                'ordering': ['alias'],
                'unique_together': {('company', 'alias')},
            },
        ),
    ]
