# Generated by Django 5.0.4 on 2026-02-20 03:20

import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Adresse email')),
                ('username', models.CharField(blank=True, help_text="Champ optionnel. L'email est utilisé pour la connexion.", max_length=150, null=True, verbose_name="Nom d'utilisateur")),
                ('first_name', models.CharField(max_length=150, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=150, verbose_name='Nom')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Numéro de téléphone')),
                ('role', models.CharField(choices=[('admin', 'Administrateur'), ('manager', 'Manager'), ('agent', 'Agent')], db_index=True, default='agent', max_length=20, verbose_name='Rôle')),
                ('status', models.CharField(choices=[('pending', "En attente d'approbation"), ('approved', 'Approuvé'), ('rejected', 'Rejeté'), ('active', 'Actif'), ('suspended', 'Suspendu')], db_index=True, default='pending', max_length=20, verbose_name='Statut du compte')),
                ('permissions_list', models.JSONField(blank=True, default=list, help_text="Liste des permissions accordées à cet utilisateur. Stockée dans le payload JWT pour éviter des requêtes DB à chaque appel. Exemples : ['view-dashboard', 'export-reports', 'manage-alerts']", verbose_name='Liste des permissions')),
                ('token_version', models.PositiveIntegerField(default=0, help_text='Incrémentée à chaque changement ou reset de mot de passe. Tous les tokens contenant une version inférieure sont automatiquement invalidés.', verbose_name='Version du token')),
                ('must_change_password', models.BooleanField(default=False, help_text="Mis à True lors de la création d'un compte agent par un manager. L'agent est forcé de changer son mot de passe temporaire au premier login.", verbose_name='Doit changer son mot de passe')),
                ('is_verified', models.BooleanField(default=False, help_text="True après validation de l'email par l'admin (pour les managers).", verbose_name='Email vérifié')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('rejection_reason', models.TextField(blank=True, help_text="Renseigné par l'admin lors du rejet ou de la suspension du compte.", null=True, verbose_name='Motif de rejet / suspension')),
                ('branch', models.ForeignKey(blank=True, help_text="Succursale assignée à l'utilisateur. Null pour les admins.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='branches.branch', verbose_name='Succursale')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_users', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
                'db_table': 'auth_user',
                'ordering': ['-created_at'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
