# Generated by Django 5.0.4 on 2026-02-21 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_user_managers'),
        ('companies', '0002_alter_company_is_active_alter_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='company',
            field=models.ForeignKey(blank=True, help_text="Société à laquelle appartient l'utilisateur. Null pour les admins.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='companies.company', verbose_name='Société'),
        ),
    ]
