# Generated by Django 5.0.4 on 2026-02-22 22:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_user_company'),
        ('branches', '0002_alter_branch_options_alter_branch_address_and_more'),
        ('companies', '0003_alter_company_options_alter_company_address_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-created_at'], 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterField(
            model_name='user',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Branch assigned to the user. Null for admins.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='branches.branch', verbose_name='Branch'),
        ),
        migrations.AlterField(
            model_name='user',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Company the user belongs to. Null for admins.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='companies.company', verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_users', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=150, verbose_name='First name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='True after admin verifies the email (for managers).', verbose_name='Email verified'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=150, verbose_name='Last name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='must_change_password',
            field=models.BooleanField(default=False, help_text='Set to True when creating an agent account by a manager. Forces the agent to change the temporary password on first login.', verbose_name='Must change password'),
        ),
        migrations.AlterField(
            model_name='user',
            name='permissions_list',
            field=models.JSONField(blank=True, default=list, help_text="List of permissions granted to this user. Stored in the JWT payload to avoid DB queries on every request. Examples: ['view-dashboard', 'export-reports', 'manage-alerts']", verbose_name='Permissions list'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone number'),
        ),
        migrations.AlterField(
            model_name='user',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Provided by admin when rejecting or suspending the account.', null=True, verbose_name='Rejection / suspension reason'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('manager', 'Manager'), ('agent', 'Agent')], db_index=True, default='agent', max_length=20, verbose_name='Role'),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('active', 'Active'), ('suspended', 'Suspended')], db_index=True, default='pending', max_length=20, verbose_name='Account status'),
        ),
        migrations.AlterField(
            model_name='user',
            name='token_version',
            field=models.PositiveIntegerField(default=0, help_text='Incremented on every password change or reset. All tokens with a lower version are automatically invalidated.', verbose_name='Token version'),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Last modified'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, help_text='Optional field. Email is used for login.', max_length=150, null=True, verbose_name='Username'),
        ),
    ]
