# Generated by Django 5.0.4 on 2026-03-16 23:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_remove_user_branch'),
        ('companies', '0004_company_city_company_country_company_current_erp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Company the user belongs to. Null for admins .', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='companies.company', verbose_name='Company'),
        ),
    ]
